"""RDL Core v0: framework-independent semantic contracts."""

from .contracts import (
    AuthorityConstraint,
    BoundaryContext,
    BoundaryInputValue,
    BoundaryValue,
    FrozenBoundaryValue,
    freeze_boundary_value,
    CommitmentOrigin,
    CommitmentRecord,
    EvidencePolarity,
    Provenance,
)
from .constraint_types import (
    ConstraintActivation,
    ConstraintEvaluation,
    ConstraintEvaluationComparison,
    ConstraintEvaluationDelta,
    ConstraintEvaluationWeights,
    ConstraintIdentity,
    RelationSemanticKey,
    ConstraintStrength,
    evaluate_constraint_strength,
    record_constraint_evaluation,
)
from .relation_types import (
    NodeDescription,
    NodeDescriptionGraph,
    RelationObservation,
    RelationObservationStatus,
    RelationTargetScope,
)
from .trigger_types import (
    MatchingObservation,
    MatchingObservationStatus,
    TriggerDescription,
    exact_key_matches,
    normalize_exact_key_text,
    observe_exact_keys,
)
from .function_types import FunctionDescription, FunctionInvocation
from .similarity_types import (
    RelationConstraintProfile,
    FunctionEvaluationComparison,
    RelationSimilarityObservation,
    SimilarityObservationStatus,
    compare_relation_constraint_polarity,
    compare_relation_constraint_provenance,
    compare_relation_constraint_profiles,
)
from .function_comparison_types import FunctionComparison
from .function_composition_types import FunctionComposition
from .evolution_types import (
    AdaptiveMBProfile,
    CompilationRecord,
    CompilationValidationStatus,
    FunctionCandidate,
    SimilarityMetric,
    SimilarityVector,
    StructureCandidate,
    extract_structure_candidate,
)

__all__ = [
    "AuthorityConstraint",
    "BoundaryContext",
    "BoundaryInputValue",
    "BoundaryValue",
    "FrozenBoundaryValue",
    "freeze_boundary_value",
    "CommitmentOrigin",
    "CommitmentRecord",
    "EvidencePolarity",
    "Provenance",
    "ConstraintActivation",
    "ConstraintEvaluation",
    "ConstraintEvaluationComparison",
    "ConstraintEvaluationDelta",
    "ConstraintEvaluationWeights",
    "ConstraintIdentity",
    "RelationSemanticKey",
    "ConstraintStrength",
    "evaluate_constraint_strength",
    "record_constraint_evaluation",
    "NodeDescription",
    "NodeDescriptionGraph",
    "RelationObservation",
    "RelationObservationStatus",
    "RelationTargetScope",
    "MatchingObservation",
    "MatchingObservationStatus",
    "TriggerDescription",
    "observe_exact_keys",
    "exact_key_matches",
    "normalize_exact_key_text",
    "FunctionDescription",
    "FunctionInvocation",
    "RelationConstraintProfile",
    "FunctionEvaluationComparison",
    "RelationSimilarityObservation",
    "SimilarityObservationStatus",
    "compare_relation_constraint_profiles",
    "compare_relation_constraint_polarity",
    "compare_relation_constraint_provenance",
    "FunctionComparison",
    "FunctionComposition",
    "SimilarityMetric",
    "SimilarityVector",
    "AdaptiveMBProfile",
    "StructureCandidate",
    "FunctionCandidate",
    "CompilationRecord",
    "CompilationValidationStatus",
    "extract_structure_candidate",
]
