"""RDL Core v0: framework-independent semantic contracts."""

from .contracts import (
    AuthorityConstraint,
    BoundaryContext,
    BoundaryInputValue,
    BoundaryValue,
    FrozenBoundaryValue,
    freeze_boundary_value,
    CommitmentOrigin,
    CommitmentRecord,
    EvidencePolarity,
    Provenance,
)
from .constraint_types import (
    ConstraintActivation,
    ConstraintEvaluation,
    ConstraintEvaluationComparison,
    ConstraintEvaluationDelta,
    ConstraintEvaluationWeights,
    ConstraintIdentity,
    ConstraintStrength,
    evaluate_constraint_strength,
    record_constraint_evaluation,
)
from .relation_types import (
    NodeDescription,
    NodeDescriptionGraph,
    RelationObservation,
    RelationObservationStatus,
    RelationTargetScope,
)
from .trigger_types import (
    MatchingObservation,
    MatchingObservationStatus,
    TriggerDescription,
    exact_key_matches,
    normalize_exact_key_text,
    observe_exact_keys,
)

__all__ = [
    "AuthorityConstraint",
    "BoundaryContext",
    "BoundaryInputValue",
    "BoundaryValue",
    "FrozenBoundaryValue",
    "freeze_boundary_value",
    "CommitmentOrigin",
    "CommitmentRecord",
    "EvidencePolarity",
    "Provenance",
    "ConstraintActivation",
    "ConstraintEvaluation",
    "ConstraintEvaluationComparison",
    "ConstraintEvaluationDelta",
    "ConstraintEvaluationWeights",
    "ConstraintIdentity",
    "ConstraintStrength",
    "evaluate_constraint_strength",
    "record_constraint_evaluation",
    "NodeDescription",
    "NodeDescriptionGraph",
    "RelationObservation",
    "RelationObservationStatus",
    "RelationTargetScope",
    "MatchingObservation",
    "MatchingObservationStatus",
    "TriggerDescription",
    "observe_exact_keys",
    "exact_key_matches",
    "normalize_exact_key_text",
]
